"""add_linkedin_url_snippet_description_to_search_results

Revision ID: fbaf68f70273
Revises: 
Create Date: 2026-01-17 16:48:58.872787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbaf68f70273'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_results', sa.Column('linkedin_url', sa.String(length=768), nullable=True))
    op.add_column('search_results', sa.Column('snippet', sa.Text(), nullable=True))
    op.add_column('search_results', sa.Column('description', sa.Text(), nullable=True))
    op.create_index(op.f('ix_search_results_linkedin_url'), 'search_results', ['linkedin_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_results_linkedin_url'), table_name='search_results')
    op.drop_column('search_results', 'description')
    op.drop_column('search_results', 'snippet')
    op.drop_column('search_results', 'linkedin_url')
    # ### end Alembic commands ###
